--Organizational Hierarchy Explorer

CREATE TABLE EMPLOYEE (
  EmpID int,
  Ename varchar(15),
  Department varchar(10),
  ManagerID int
);

INSERT INTO EMPLOYEE VALUES (1, 'Alice', 'HR',NULL);
INSERT INTO EMPLOYEE VALUES (2, 'Bob', 'Finance',1);
INSERT INTO EMPLOYEE VALUES (3, 'Charlie', 'IT',1);
INSERT INTO EMPLOYEE VALUES (4, 'David', 'FInance',2);
INSERT INTO EMPLOYEE VALUES (5, 'Eve', 'IT',3);
INSERT INTO EMPLOYEE VALUES (6, 'Frank', 'HR',1);


--SELECT * FROM EMPLOYEE;
SELECT E.Ename AS [EMPLYEE NAME],E2.Ename AS [MANAGER NAME],
E.Department AS [EMPLOYEE DEPARTMENT],E2.DEPARTMENT AS [MANAGER DEPARTMENT]
FROM
EMPLOYEE AS E
LEFT JOIN
EMPLOYEE AS E2
ON
E.ManagerID=E2.EmpID


--NPV Lookup Using Left Join
CREATE TABLE Year_tbl(
  ID int,
  YEAR int,
  NPV int,
);
TRUNCATE TABLE Year_tbl;
INSERT INTO Year_tbl VALUES(1,2018,100);
INSERT INTO Year_tbl VALUES(7,2020,30);
INSERT INTO Year_tbl VALUES(13,2019,40);
INSERT INTO Year_tbl VALUES(1,2019,113);
INSERT INTO Year_tbl VALUES(2,2008,121);
INSERT INTO Year_tbl VALUES(3,2009,12);
INSERT INTO Year_tbl VALUES(11,2020,99);
INSERT INTO Year_tbl VALUES(7,2019,0);

--SELECT * FROM Year_tbl;

CREATE TABLE Queries_tbl(
  ID int,
  YEAR int
);
INSERT INTO Queries_tbl VALUES(1,2019);
INSERT INTO Queries_tbl VALUES(2,2008);
INSERT INTO Queries_tbl VALUES(3,2009);
INSERT INTO Queries_tbl VALUES(7,2018);
INSERT INTO Queries_tbl VALUES(7,2019);
INSERT INTO Queries_tbl VALUES(7,2020);
INSERT INTO Queries_tbl VALUES(13,2019);
--SELECT * FROM Queries_tbl;

SELECT Q.ID,Q.YEAR,ISNULL(Y.NPV,0)AS NPV
FROM Queries_tbl AS Q 
LEFT OUTER JOIN
Year_tbl AS Y 
ON 
Y.ID=Q.ID
and
Y.YEAR=Q.YEAR
